import os

def Settings( **kwargs ):
    workarea = os.environ["WORKAREA"]
    chipname = os.environ["CHIPNAME"] # S9 / S9m
    return {
        'flags': [
            '-x',
            'c++',
            "-Wall",
            "-std c++11",
            "-Wextra",
            "-Wno-parentheses",
            "-Wno-unused-parameter",
            "-DBOOST_ALL_NO_LIB",
            "-DBOOST_LOG_DYN_LINK",
            "-DISCTLM_NOWARN_DEPRECATED_SCBTLM=1",
            "-DPROJECT_NAME=" + chipname.upper(),
            "-DPROJECT_" + chipname.upper(),
            "-DSC_CPLUSPLUS=199711L",
            "-DSC_INCLUDE_DYNAMIC_PROCESSES",
            "-DSC_INCLUDE_FX",
            "-DUSE_SYSTEMVP",
            "-I.",
            "-I" + workarea + "/ci/units/ci_cgu/source/sc/beh",
            "-I" + workarea + "/ci/units/ci_cgu/xml_gen/sc",
            "-I" + workarea + "/ci/units/ci_data_tracing_unit/source/sc/beh",
            "-I" + workarea + "/ci/units/ci_data_tracing_unit/xml_gen/sc",
            "-I" + workarea + "/ci/units/ci_gnss_trace/source/sc/beh",
            "-I" + workarea + "/ci/units/ci_gnss_trace/xml_gen/sc",
            "-I" + workarea + "/ci/units/ci_lt/source/sc/beh",
            "-I" + workarea + "/ci/units/ci_lt/xml_gen/sc",
            "-I" + workarea + "/ci/units/ci_mems_regs/source/sc/beh",
            "-I" + workarea + "/ci/units/ci_mems_regs/xml_gen/sc",
            "-I" + workarea + "/ci/units/ci_mi/source/sc/beh",
            "-I" + workarea + "/ci/units/ci_mi/xml_gen/sc",
            "-I" + workarea + "/ci/units/ci_noc2gnss_bridge/source/sc/beh",
            "-I" + workarea + "/ci/units/ci_noc2gnss_bridge/xml_gen/sc",
            "-I" + workarea + "/ci/units/ci_rfc/source/sc/beh",
            "-I" + workarea + "/ci/units/ci_rfc/xml_gen/sc",
            "-I" + workarea + "/ci/units/ci_scon/source/sc/beh",
            "-I" + workarea + "/ci/units/ci_scon/xml_gen/arm",
            "-I" + workarea + "/ci/units/ci_scon/xml_gen/c",
            "-I" + workarea + "/ci/units/ci_scon/xml_gen/sc",
            "-I" + workarea + "/ci/units/ci_scu/source/sc/beh",
            "-I" + workarea + "/ci/units/ci_scu/xml_gen/sc",
            "-I" + workarea + "/ci/units/ci_sysacc/source/sc/beh",
            "-I" + workarea + "/ci/units/ci_sysacc/xml_gen/sc",
            "-I" + workarea + "/ci/units/ci_top/source/sc/beh",
            "-I" + workarea + "/ci/units/ci_top/xml_gen/arm",
            "-I" + workarea + "/ci/units/ci_top/xml_gen/c",
            "-I" + workarea + "/ci/units/ci_top/xml_gen/sc",
            "-I" + workarea + "/ci/units/ci_trace_unit/source/sc/beh",
            "-I" + workarea + "/ci/units/ci_trace_unit/xml_gen/sc",
            "-I" + workarea + "/com/units/com_mems_regs/source/sc/beh",
            "-I" + workarea + "/com/units/com_mems_regs/xml_gen/sc",
            "-I" + workarea + "/com/units/com_rfc_rffe/source/sc/beh",
            "-I" + workarea + "/com/units/com_rfc_rffe/xml_gen/sc",
            "-I" + workarea + "/com/units/com_semaphore/source/sc/beh",
            "-I" + workarea + "/com/units/com_semaphore/xml_gen/sc",
            "-I" + workarea + "/com/units/com_streaming/source/sc/beh",
            "-I" + workarea + "/com/units/com_tb/source/sc/beh",
            "-I" + workarea + "/com/units/com_tb/xml_gen/sc",
            "-I" + workarea + "/com/units/common/source/sc/beh",
            "-I" + workarea + "/com/units/common/xml_gen/sc",
            "-I" + workarea + "/com/units/lbtrc/source/sc/beh",
            "-I" + workarea + "/com/units/lbtrc/xml_gen/sc",
            "-I" + workarea + "/com/units/llmh/source/sc/beh",
            "-I" + workarea + "/com/units/llmh/xml_gen/sc",
            "-I" + workarea + "/com/units/local_bus/source/sc/beh",
            "-I" + workarea + "/com/units/local_bus/xml_gen/sc",
            "-I" + workarea + "/com/units/lt/source/sc/beh",
            "-I" + workarea + "/com/units/lt/xml_gen/sc",
            "-I" + workarea + "/com/units/noc/source/sc/beh",
            "-I" + workarea + "/com/units/noc/xml_gen/sc",
            "-I" + workarea + "/com/units/sscript_ng_rfec/source/sc/beh",
            "-I" + workarea + "/com/units/sscript_ng_rfec/xml_gen/sc",
            "-I" + workarea + "/com/units/tlp/source/sc/beh",
            "-I" + workarea + "/com/units/tlp/xml_gen/sc",
            "-I" + workarea + "/dpll/units/dpll_ci/source/sc/beh",
            "-I" + workarea + "/dpll/units/dpll_ci/xml_gen/sc",
            "-I" + workarea + "/dpll/units/dpll_com/source/sc/beh",
            "-I" + workarea + "/dpll/units/dpll_com/xml_gen/sc",
            "-I" + workarea + "/dpll/units/dpll_mems_regs/source/sc/beh",
            "-I" + workarea + "/dpll/units/dpll_mems_regs/xml_gen/sc",
            "-I" + workarea + "/srftools/lib/sc/interfaces/beh",
            "-I" + workarea + "/srftools/lib/sc/lookup/beh",
            "-I" + workarea + "/srftools/lib/sc/meta_utils/beh",
            "-I" + workarea + "/srftools/lib/sc/noc_utils/beh",
            "-I" + workarea + "/srftools/lib/sc/scon_utils/beh",
            "-I" + workarea + "/srftools/lib/sc/tb_utils/beh",
            "-I" + workarea + "/srftools/lib/sc/tlm4rf/beh",
            "-I" + workarea + "/srftools/lib/sc/utils/beh",
            "-isystem",
            "/p/inway/eda/opensource/systemc/2.3.1/systemc-2.3.1/inst/include",
            "-isystem",
            "/p/inway/tools/opensource/boost/1.57.0/share/include",
            "-isystem",
            workarea + "/resources/isctlm/incl",
            "-isystem",
            workarea + "/resources/isctlm/incl/scb_utils/",
        ]
    }

