import os

def Settings( **kwargs ):
    workarea = os.environ["WORKAREA"]
    chipname = os.environ["CHIPNAME"] # S9 / S9m
    return {
        'flags': [
            '-x',
            'c++',
            "-Wall",
            "-std c++11",
            "-Wextra",
            "-Wno-parentheses",
            "-Wno-unused-parameter",
            "-DBOOST_ALL_NO_LIB",
            "-DBOOST_LOG_DYN_LINK",
            "-DISCTLM_NOWARN_DEPRECATED_SCBTLM=1",
            "-DPROJECT_NAME=" + chipname.upper(),
            "-DPROJECT_" + chipname.upper(),
            "-DSC_CPLUSPLUS=199711L",
            "-DSC_INCLUDE_DYNAMIC_PROCESSES",
            "-DSC_INCLUDE_FX",
            "-DUSE_SYSTEMVP",
            "-I.",
            "-isystem",
            "/p/msocip/sscript/v2.05/lib/angelscript/sdk/add_on/enum_print",
            "-isystem",
            "/p/msocip/sscript/v2.05/lib/angelscript/sdk/add_on/scriptany",
            "-isystem",
            "/p/msocip/sscript/v2.05/lib/angelscript/sdk/add_on/scriptarray",
            "-isystem",
            "/p/msocip/sscript/v2.05/lib/angelscript/sdk/add_on/scriptbuilder",
            "-isystem",
            "/p/msocip/sscript/v2.05/lib/angelscript/sdk/add_on/scriptdictionary",
            "-isystem",
            "/p/msocip/sscript/v2.05/lib/angelscript/sdk/add_on/scriptdictionary/../scriptarray",
            "-isystem",
            "/p/msocip/sscript/v2.05/lib/angelscript/sdk/add_on/scripthandle",
            "-isystem",
            "/p/msocip/sscript/v2.05/lib/angelscript/sdk/add_on/scripthelper",
            "-isystem",
            "/p/msocip/sscript/v2.05/lib/angelscript/sdk/add_on/scriptmath",
            "-isystem",
            "/p/msocip/sscript/v2.05/lib/angelscript/sdk/add_on/scriptstdstring",
            "-isystem",
            "/p/msocip/sscript/v2.05/lib/angelscript/sdk/add_on/scriptstdstring/../scriptarray",
            "-isystem",
            "/p/msocip/sscript/v2.05/lib/angelscript/sdk/angelscript/include",
            "-isystem",
            "/p/msocip/sscript/v2.05/lib/angelscript/sdk/angelscript/source",
            "-isystem",
            "/p/msocip/sscript/v2.05/lib/angelscript/sdk/angelscript/source/../include",
            "-isystem",
            "/p/msocip/sscript/v2.05/lib/debugger/include",
            "-isystem",
            "/p/msocip/sscript/v2.05/lib/prefix_ostream_filter/include",
            "-isystem",
            "/p/msocip/sscript/v2.05/lib/rpc/include",
            "-isystem",
            "/p/msocip/sscript/v2.05/lib/smarti_script_ng/include",
            "-isystem",
            "/p/msocip/sscript/v2.05/lib/smarti_script_ng/include/../source",
            "-isystem",
            "/p/msocip/sscript/v2.05/lib/smarti_script_ng/source",
            "-isystem",
            "/p/msocip/sscript/v2.05/lib/smarti_script_ng/source/../source",
            "-isystem",
            "/p/msocip/sscript/v2.05/lib/sscript_ng_filesystem/include",
            "-isystem",
            "/p/msocip/sscript/v2.05/lib/sscript_ng_framebox/include",
            "-I" + workarea + "/ci/units/ci_sysacc/source/sc/beh",
            "-I" + workarea + "/ci/units/ci_top/source/sc/beh/../../../xml_gen/sc",
            "-I" + workarea + "/com/units/com_cpu/source/sc/beh",
            "-I" + workarea + "/com/units/com_hls_ctos/source/sc/beh/../hls/ctos_flex_channels",
            "-I" + workarea + "/com/units/com_instr_cntrl_if/source/sc/beh",
            "-I" + workarea + "/com/units/com_mems_regs/source/sc/beh",
            "-I" + workarea + "/com/units/com_mems_regs/xml_gen/sc",
            "-I" + workarea + "/com/units/com_rfc_rffe/source/sc/beh",
            "-I" + workarea + "/com/units/com_semaphore/source/sc/beh",
            "-I" + workarea + "/com/units/com_streaming/source/sc/beh",
            "-I" + workarea + "/com/units/com_tb/source/sc/beh",
            "-I" + workarea + "/com/units/common/source/sc/beh",
            "-I" + workarea + "/com/units/dbdma/source/sc/beh",
            "-I" + workarea + "/com/units/dmac/source/sc/beh",
            "-I" + workarea + "/com/units/hlmh/source/sc/beh",
            "-I" + workarea + "/com/units/irc/source/sc/beh",
            "-I" + workarea + "/com/units/lbtrc/source/sc/beh",
            "-I" + workarea + "/com/units/llmh/source/sc/beh",
            "-I" + workarea + "/com/units/local_bus/source/sc/beh",
            "-I" + workarea + "/com/units/lt/source/sc/beh",
            "-I" + workarea + "/com/units/noc/source/sc/beh",
            "-I" + workarea + "/com/units/sscript_ng/source/sc/beh",
            "-I" + workarea + "/com/units/sscript_ng_rfec/source/sc/beh",
            "-I" + workarea + "/com/units/tlp/source/sc/beh",
            "-I" + workarea + "/com/units/xbar/source/sc/beh",
            "-I" + workarea + "/rx/units/rx_top/source/sc/beh/../../../xml_gen/sc",
            "-I" + workarea + "/srftools/lib/sc/interfaces/beh",
            "-I" + workarea + "/srftools/lib/sc/lookup/beh",
            "-I" + workarea + "/srftools/lib/sc/meta_utils/beh",
            "-I" + workarea + "/srftools/lib/sc/noc_utils/beh",
            "-I" + workarea + "/srftools/lib/sc/scon_utils/beh",
            "-I" + workarea + "/srftools/lib/sc/tb_utils/beh",
            "-I" + workarea + "/srftools/lib/sc/tlm4rf/beh",
            "-I" + workarea + "/srftools/lib/sc/utils/beh",
            "-I" + workarea + "/top/units/top/source/sc/beh",
            "-I" + workarea + "/top/units/top/xml_gen/sc",
            "-isystem",
            "/p/inway/tools/opensource/boost/1.57.0/share/include",
            "-isystem",
            "/p/inway/eda/opensource/systemc/2.3.1/systemc-2.3.1/inst/include",
            "-isystem",
            workarea + "/resources/isctlm/incl",
            "-isystem",
            workarea + "/resources/isctlm/incl/scb_utils/",
            "-isystem",
            "/p/inway/eda/opensource/scml/2.4.1/inst/include",
        ]
    }
