import os

def Settings( **kwargs ):
    workarea = os.environ["WORKAREA"]
    chipname = os.environ["CHIPNAME"] # S9 / S9m
    return {
        'flags': [
            '-x',
            'c++',
            "-Wall",
            "-std c++11",
            "-Wextra",
            "-Wno-parentheses",
            "-Wno-unused-parameter",
            "-DBOOST_ALL_NO_LIB",
            "-DBOOST_LOG_DYN_LINK",
            "-DISCTLM_NOWARN_DEPRECATED_SCBTLM=1",
            "-DPROJECT_NAME=" + chipname.upper(),
            "-DPROJECT_" + chipname.upper(),
            "-DSC_CPLUSPLUS=199711L",
            "-DSC_INCLUDE_DYNAMIC_PROCESSES",
            "-DSC_INCLUDE_FX",
            "-DUSE_SYSTEMVP",
            "-I.",
            "-I" + workarea + "/ci/units/ci_cgu/source/sc/beh",
            "-I" + workarea + "/ci/units/ci_cgu/xml_gen/sc",
            "-I" + workarea + "/ci/units/ci_data_tracing_unit/source/sc/beh",
            "-I" + workarea + "/ci/units/ci_data_tracing_unit/xml_gen/sc",
            "-I" + workarea + "/ci/units/ci_gnss_trace/source/sc/beh",
            "-I" + workarea + "/ci/units/ci_gnss_trace/xml_gen/sc",
            "-I" + workarea + "/ci/units/ci_lt/source/sc/beh",
            "-I" + workarea + "/ci/units/ci_lt/xml_gen/sc",
            "-I" + workarea + "/ci/units/ci_mems_regs/source/sc/beh",
            "-I" + workarea + "/ci/units/ci_mems_regs/xml_gen/sc",
            "-I" + workarea + "/ci/units/ci_mi/source/sc/beh",
            "-I" + workarea + "/ci/units/ci_mi/xml_gen/sc",
            "-I" + workarea + "/ci/units/ci_noc2gnss_bridge/source/sc/beh",
            "-I" + workarea + "/ci/units/ci_noc2gnss_bridge/xml_gen/sc",
            "-I" + workarea + "/ci/units/ci_rfc/source/sc/beh",
            "-I" + workarea + "/ci/units/ci_rfc/xml_gen/sc",
            "-I" + workarea + "/ci/units/ci_scon/source/sc/beh",
            "-I" + workarea + "/ci/units/ci_scon/xml_gen/sc",
            "-I" + workarea + "/ci/units/ci_scu/source/sc/beh",
            "-I" + workarea + "/ci/units/ci_scu/xml_gen/sc",
            "-I" + workarea + "/ci/units/ci_sysacc/source/sc/beh",
            "-I" + workarea + "/ci/units/ci_sysacc/xml_gen/sc",
            "-I" + workarea + "/ci/units/ci_top/source/sc/beh",
            "-I" + workarea + "/ci/units/ci_top/xml_gen/sc",
            "-I" + workarea + "/ci/units/ci_trace_unit/source/sc/beh",
            "-I" + workarea + "/ci/units/ci_trace_unit/xml_gen/sc",
            "-I" + workarea + "/com/units/com_coproc/source/sc/beh",
            "-I" + workarea + "/com/units/com_coproc/xml_gen/sc",
            "-I" + workarea + "/com/units/com_cpu/source/sc/beh",
            "-I" + workarea + "/com/units/com_cpu/xml_gen/sc",
            "-I" + workarea + "/com/units/com_hls/source/sc/beh",
            "-I" + workarea + "/com/units/com_hls/source/sc/hls",
            "-I" + workarea + "/com/units/com_hls/xml_gen/sc",
            "-I" + workarea + "/com/units/com_hls_base/source/sc/beh",
            "-I" + workarea + "/com/units/com_hls_base/source/sc/hls",
            "-I" + workarea + "/com/units/com_hls_base/xml_gen/sc",
            "-I" + workarea + "/com/units/com_hls_ctos/source/sc/beh",
            "-I" + workarea + "/com/units/com_hls_ctos/source/sc/beh/../hls/ctos_clock_gating",
            "-I" + workarea + "/com/units/com_hls_ctos/source/sc/beh/../hls/ctos_flex_channels",
            "-I" + workarea + "/com/units/com_hls_ctos/source/sc/beh/../hls/ctos_flex_channels/ctos_put_get_channels",
            "-I" + workarea + "/com/units/com_hls_ctos/source/sc/beh/../hls/ctos_fx",
            "-I" + workarea + "/com/units/com_hls_ctos/source/sc/beh/../hls/ctos_tlm",
            "-I" + workarea + "/com/units/com_hls_ctos/source/sc/beh/../hls/ctos_tlm/ctos_tlm_adapters",
            "-I" + workarea + "/com/units/com_hls_ctos/source/sc/beh/../hls/ctos_tlm/ctos_tlm_event_finder",
            "-I" + workarea + "/com/units/com_hls_ctos/source/sc/beh/../hls/ctos_tlm/ctos_tlm_fifo",
            "-I" + workarea + "/com/units/com_hls_ctos/source/sc/beh/../hls/ctos_tlm/ctos_tlm_fifo_1t",
            "-I" + workarea + "/com/units/com_hls_ctos/source/sc/beh/../hls/ctos_tlm/ctos_tlm_fifo_reg",
            "-I" + workarea + "/com/units/com_hls_ctos/source/sc/beh/../hls/ctos_tlm/ctos_tlm_fifo_reg_1t",
            "-I" + workarea + "/com/units/com_hls_ctos/source/sc/beh/../hls/ctos_tlm/ctos_tlm_interfaces",
            "-I" + workarea + "/com/units/com_hls_ctos/source/sc/beh/../hls/ctos_tlm/ctos_tlm_req_rsp",
            "-I" + workarea + "/com/units/com_hls_ctos/source/sc/beh/../hls/ctos_tlm/ctos_tlm_utils",
            "-I" + workarea + "/com/units/com_hls_ctos/source/sc/hls",
            "-I" + workarea + "/com/units/com_hls_ctos/xml_gen/sc",
            "-I" + workarea + "/com/units/com_instr_cntrl_if/source/sc/beh",
            "-I" + workarea + "/com/units/com_instr_cntrl_if/xml_gen/sc",
            "-I" + workarea + "/com/units/com_mems_regs/source/sc/beh",
            "-I" + workarea + "/com/units/com_mems_regs/xml_gen/sc",
            "-I" + workarea + "/com/units/com_rfc_rffe/source/sc/beh",
            "-I" + workarea + "/com/units/com_rfc_rffe/xml_gen/sc",
            "-I" + workarea + "/com/units/com_semaphore/source/sc/beh",
            "-I" + workarea + "/com/units/com_semaphore/xml_gen/sc",
            "-I" + workarea + "/com/units/com_streaming/source/sc/beh",
            "-I" + workarea + "/com/units/com_streaming/xml_gen/sc",
            "-I" + workarea + "/com/units/common/source/sc/beh",
            "-I" + workarea + "/com/units/common/xml_gen/sc",
            "-I" + workarea + "/com/units/dbdma/source/sc/beh",
            "-I" + workarea + "/com/units/dbdma/xml_gen/sc",
            "-I" + workarea + "/com/units/dmac/source/sc/beh",
            "-I" + workarea + "/com/units/dmac/xml_gen/sc",
            "-I" + workarea + "/com/units/hlmh/source/sc/beh",
            "-I" + workarea + "/com/units/hlmh/xml_gen/sc",
            "-I" + workarea + "/com/units/irc/source/sc/beh",
            "-I" + workarea + "/com/units/irc/xml_gen/sc",
            "-I" + workarea + "/com/units/lbtrc/source/sc/beh",
            "-I" + workarea + "/com/units/lbtrc/xml_gen/sc",
            "-I" + workarea + "/com/units/llmh/source/sc/beh",
            "-I" + workarea + "/com/units/llmh/xml_gen/sc",
            "-I" + workarea + "/com/units/local_bus/source/sc/beh",
            "-I" + workarea + "/com/units/local_bus/xml_gen/sc",
            "-I" + workarea + "/com/units/lt/source/sc/beh",
            "-I" + workarea + "/com/units/lt/xml_gen/sc",
            "-I" + workarea + "/com/units/noc/source/sc/beh",
            "-I" + workarea + "/com/units/noc/xml_gen/sc",
            "-I" + workarea + "/com/units/sscript_ng_rfec/source/sc/beh",
            "-I" + workarea + "/com/units/sscript_ng_rfec/xml_gen/sc",
            "-I" + workarea + "/com/units/tlp/source/sc/beh",
            "-I" + workarea + "/com/units/tlp/xml_gen/sc",
            "-I" + workarea + "/com/units/xbar/source/sc/beh",
            "-I" + workarea + "/com/units/xbar/xml_gen/sc",
            "-I" + workarea + "/dpll/units/dpll_ci/source/sc/beh",
            "-I" + workarea + "/dpll/units/dpll_ci/xml_gen/sc",
            "-I" + workarea + "/dpll/units/dpll_com/source/sc/beh",
            "-I" + workarea + "/dpll/units/dpll_com/xml_gen/sc",
            "-I" + workarea + "/dpll/units/dpll_mems_regs/source/sc/beh",
            "-I" + workarea + "/dpll/units/dpll_mems_regs/xml_gen/sc",
            "-I" + workarea + "/dpll/units/dpll_rx/source/sc/beh",
            "-I" + workarea + "/dpll/units/dpll_rx/xml_gen/sc",
            "-I" + workarea + "/dpll/units/dpll_tx/source/sc/beh",
            "-I" + workarea + "/dpll/units/dpll_tx/xml_gen/sc",
            "-I" + workarea + "/rx/units/rx_ana/source/sc/beh",
            "-I" + workarea + "/rx/units/rx_ana/xml_gen/sc",
            "-I" + workarea + "/rx/units/rx_cgu/source/sc/beh",
            "-I" + workarea + "/rx/units/rx_cgu/xml_gen/sc",
            "-I" + workarea + "/rx/units/rx_com/source/sc/beh",
            "-I" + workarea + "/rx/units/rx_com/xml_gen/sc",
            "-I" + workarea + "/rx/units/rx_cpu/source/sc/beh",
            "-I" + workarea + "/rx/units/rx_cpu/xml_gen/sc",
            "-I" + workarea + "/rx/units/rx_dfe/source/sc/beh",
            "-I" + workarea + "/rx/units/rx_dfe/source/sc/hls",
            "-I" + workarea + "/rx/units/rx_dfe/xml_gen/sc",
            "-I" + workarea + "/rx/units/rx_lt/source/sc/beh",
            "-I" + workarea + "/rx/units/rx_lt/xml_gen/sc",
            "-I" + workarea + "/rx/units/rx_mems_regs/source/sc/beh",
            "-I" + workarea + "/rx/units/rx_mems_regs/xml_gen/sc",
            "-I" + workarea + "/rx/units/rx_top/source/sc/beh",
            "-I" + workarea + "/rx/units/rx_top/xml_gen/sc",
            "-I" + workarea + "/srftools/lib/sc_hls/ctos_clock_gating",
            "-I" + workarea + "/srftools/lib/sc_hls/ctos_flex_channels",
            "-I" + workarea + "/srftools/lib/sc_hls/ctos_fx",
            "-I" + workarea + "/srftools/lib/sc_hls/ctos_tlm",
            "-I" + workarea + "/srftools/lib/sc_hls/hls_model_lib",
            "-I" + workarea + "/srftools/lib/sc_hls/hls_tb_lib",
            "-I" + workarea + "/top/units//tx_dig_iq_apc/source/sc/hls/",
            "-I" + workarea + "/top/units//tx_dig_iq_top/source/sc_hls/beh/",
            "-I" + workarea + "/top/units/gnss_vp/source/sc/beh",
            "-I" + workarea + "/top/units/gnss_vp/xml_gen/sc",
            "-I" + workarea + "/top/units/top/source/sc/beh",
            "-I" + workarea + "/top/units/top/xml_gen/arm",
            "-I" + workarea + "/top/units/top/xml_gen/c",
            "-I" + workarea + "/top/units/top/xml_gen/sc",
            "-I" + workarea + "/top/units/top_fe_common/source/sc/beh",
            "-I" + workarea + "/top/units/top_fe_common/xml_gen/sc",
            "-I" + workarea + "/top/units/top_ice20/source/sc/beh",
            "-I" + workarea + "/top/units/top_ice20/xml_gen/sc",
            "-I" + workarea + "/top/units/top_intel_es1/source/sc/beh",
            "-I" + workarea + "/top/units/top_intel_es1/xml_gen/sc",
            "-I" + workarea + "/top/units/top_intel_es2/source/sc/beh",
            "-I" + workarea + "/top/units/top_intel_es2/xml_gen/sc",
            "-I" + workarea + "/tx/units/tx_ana/source/sc/beh",
            "-I" + workarea + "/tx/units/tx_ana/xml_gen/sc",
            "-I" + workarea + "/tx/units/tx_cgu/source/sc/beh",
            "-I" + workarea + "/tx/units/tx_cgu/xml_gen/sc",
            "-I" + workarea + "/tx/units/tx_cpu/source/sc/beh",
            "-I" + workarea + "/tx/units/tx_cpu/xml_gen/sc",
            "-I" + workarea + "/tx/units/tx_dfe/source/sc/beh",
            "-I" + workarea + "/tx/units/tx_dfe/source/sc/hls",
            "-I" + workarea + "/tx/units/tx_dfe/xml_gen/sc",
            "-I" + workarea + "/tx/units/tx_dig_iq_apc/source/sc/beh",
            "-I" + workarea + "/tx/units/tx_dig_iq_apc/source/sc/hls",
            "-I" + workarea + "/tx/units/tx_dig_iq_apc/xml_gen/sc",
            "-I" + workarea + "/tx/units/tx_dig_iq_asrc/source/sc/beh",
            "-I" + workarea + "/tx/units/tx_dig_iq_asrc/source/sc/hls",
            "-I" + workarea + "/tx/units/tx_dig_iq_asrc/xml_gen/sc",
            "-I" + workarea + "/tx/units/tx_dig_iq_dig_et/source/sc/beh",
            "-I" + workarea + "/tx/units/tx_dig_iq_dig_et/source/sc/hls",
            "-I" + workarea + "/tx/units/tx_dig_iq_dig_et/xml_gen/sc",
            "-I" + workarea + "/tx/units/tx_dig_iq_fbr/source/sc/beh",
            "-I" + workarea + "/tx/units/tx_dig_iq_fbr/source/sc/hls",
            "-I" + workarea + "/tx/units/tx_dig_iq_fbr/xml_gen/sc",
            "-I" + workarea + "/tx/units/tx_dig_iq_mdpd/source/sc/beh",
            "-I" + workarea + "/tx/units/tx_dig_iq_mdpd/source/sc/hls",
            "-I" + workarea + "/tx/units/tx_dig_iq_mdpd/xml_gen/sc",
            "-I" + workarea + "/tx/units/tx_dig_iq_top/source/sc/beh",
            "-I" + workarea + "/tx/units/tx_dig_iq_top/source/sc/hls",
            "-I" + workarea + "/tx/units/tx_dig_iq_top/xml_gen/sc",
            "-I" + workarea + "/tx/units/tx_lt/source/sc/beh",
            "-I" + workarea + "/tx/units/tx_lt/xml_gen/sc",
            "-I" + workarea + "/tx/units/tx_mems_regs/source/sc/beh",
            "-I" + workarea + "/tx/units/tx_mems_regs/xml_gen/sc",
            "-I" + workarea + "/tx/units/tx_top/source/sc/beh",
            "-I" + workarea + "/tx/units/tx_top/xml_gen/sc",
            "-I" + workarea + "/srftools/lib/sc/tb_utils/beh",
            "-I" + workarea + "/srftools/lib/sc/build_info/beh",
            "-I" + workarea + "/srftools/lib/sc/vp_hls/beh",
            "-I" + workarea + "/srftools/lib/sc/mixed_abstraction_utils/beh",
            "-I" + workarea + "/srftools/lib/sc/suti_utils/beh",
            "-I" + workarea + "/srftools/lib/sc/fe_utils/beh",
            "-I" + workarea + "/srftools/lib/sc/noc_utils/beh",
            "-I" + workarea + "/srftools/lib/sc/utils/beh",
            "-I" + workarea + "/srftools/lib/sc/tlm4rf/beh",
            "-I" + workarea + "/srftools/lib/sc/scon_utils/beh",
            "-I" + workarea + "/srftools/lib/sc/lookup/beh",
            "-I" + workarea + "/srftools/lib/sc/meta_utils/beh",
            "-I" + workarea + "/srftools/lib/sc/interfaces/beh",
            "-isystem /p/inway/tools/opensource/boost/1.57.0/share/include",
            "-isystem",
            "/p/inway/eda/opensource/systemc/2.3.1/systemc-2.3.1/inst/include",
            "-isystem",
            "" + workarea + "/resources/isctlm/incl",
            "-isystem " + workarea + "/resources/isctlm/incl/scb_utils/",
            "-isystem /p/inway/eda/opensource/scml/2.4.1/inst/include",
        ]
    }
